### ISSUE TITLE
Authorship policy

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt-4.0-paper#1]
I've drafted an authorship policy and included it in README.md.  Discussion and suggestions for changes can go here.

**Comment by ngoldbaum** [comment]
I don't see this text. Did you forget to push or am I looking at the wrong place?

**Comment by MatthewTurk** [comment]
Nope, you were looking at the right place.  I didn't forget to push; I forgot to commit before pushing.  :)  Now it's fixed.

**Comment by matthewturk** [comment]
I believe the authorship policy is now roughly stable, and I am closing.
