### ISSUE TITLE
User friendliness

### ISSUE THREAD

**Issue by matthewturk** [yt-project/yt-4.0-paper#109]
The entire section "User friendliness" is currently empty and needs filling.  Specfifically, this includes right now:

 - [x] Publication-quality plots
 - [x] Jupyter Integration

I will reference the widgyts paper in the latter, and discuss the choice of default values in the former.

I think there's also room for a section about the type hinting and error message improvements.

**Comment by neutrinoceros** [comment]
> error message improvements.

big +1 here

**Comment by matthewturk** [comment]
I mean, you did a lot of that work, so I am glad you are ok with me writing about it!  :)
