### ISSUE TITLE
Broken javascript code

### ISSUE THREAD

**Issue by neutrinoceros** [yt-project/yt-4.0-paper#66]
In the "Indexing and Geometry" section, there's a beautiful D3 script that translates a logically-cartesian grid to a real-space one, but the connexions (appearing as the mouse hovers the cells) do not all make sense
Here's an example of a broken one
<img width="615" alt="Screenshot 2021-04-18 at 16 30 06" src="https://user-images.githubusercontent.com/14075922/115149296-b1cada80-a063-11eb-92ef-051df155d448.png">

I'd fix this if I knew javascript + D3

**Comment by matthewturk** [comment]
I noticed this and was hoping to fix it before anyone else did!  :-)

**Comment by neutrinoceros** [comment]
I confirm this is fixed, well played !
